version: "3"
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wakanda
      MYSQL_DATABASE: wakanda_db
      MYSQL_USER: wakanda
      MYSQL_PASSWORD: wakanda
      TZ: America/Sao_Paulo
    volumes:
      - "./docker/dev/database:/var/lib/mysql"
    ports:
      - "3306:3306"